version: '3.3'

services:
  db:
    image: mysql:8.0
    volumes:
      - ./wordpress.sql:/docker-entrypoint-initdb.d/init.sql # prepopulate database
      - db_data:/var/lib/mysql # persist database data inside docker storage
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - .env
    environment:
      DOCKER_COMPOSE_YML_LOCATION: ${PWD}
    container_name: ${CONTAINER_DB}
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      DOCKER_COMPOSE_YML_LOCATION: ${PWD}
    volumes:
      - ./html:/var/www/html
    container_name: ${CONTAINER_WP}
volumes:
  db_data: {}
